---
# tasks file for vicenteg.mapr_myriad_startup

- name: copy marathon app configuration
  template: src=resourcemanager.json.j2 dest=/tmp/resourcemanager.json mode=0600

- name: find marathon
  command: curl -L -s http://localhost:5050/frameworks | jq -r '.frameworks[] | select(.name == "marathon") | .webui_url'
  register: marathon_webui

- name: wait for marathon to be listening
  wait_for: port={{marathon_port}} timeout=120
  tags: test

- name: create new marathon app
  command: 'curl -X POST -H "Content-Type: application/json" http://{{marathon_webui}}/v2/apps -d @/tmp/resourcemanager.json'
  run_once: yes
