---
# tasks file for vicenteg.mapr_myriad_startup

- name: copy marathon app configuration
  template: src=resourcemanager.json.j2 dest=/tmp/resourcemanager.json mode=0600

- name: find marathon
  shell: "curl -L -s http://{{ansible_fqdn}}:5050/frameworks | jq -r '.frameworks[] | select(.name == \"marathon\") | .webui_url'"
  register: marathon_webui

- name: wait for marathon to be listening
  wait_for: port={{marathon_port}} timeout=120
  tags: test

- name: create new marathon app
  command: 'curl -X POST -H "Content-Type: application/json" {{marathon_webui.stdout}}/v2/apps -d @/tmp/resourcemanager.json'
  run_once: yes
